# -*- coding: utf-8 -*-
"""CodeSoft_Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jvastZB9qzOPjQmer4mcuF4abbLV7_x4
"""

#TASK 4 Rock-Paper-Scissors Game

import random

def get_user_choice():
    user_choice = input("Choose rock, paper, or scissors: ")
    while user_choice not in ["rock", "paper", "scissors"]:
        user_choice = input("Invalid choice. Choose rock, paper, or scissors: ")
    return user_choice

def get_computer_choice():
    computer_choice = random.choice(["rock", "paper", "scissors"])
    return computer_choice

def determine_winner(user_choice, computer_choice):
    if user_choice == computer_choice:
        return "Tie"
    elif user_choice == "rock":
        if computer_choice == "scissors":
            return "User wins!"
        else:
            return "Computer wins!"
    elif user_choice == "paper":
        if computer_choice == "rock":
            return "User wins!"
        else:
            return "Computer wins!"
    elif user_choice == "scissors":
        if computer_choice == "paper":
            return "User wins!"
        else:
            return "Computer wins!"

def display_results(user_choice, computer_choice, winner):
    print("You chose:", user_choice)
    print("Computer chose:", computer_choice)
    print(winner)

if __name__ == "__main__":
    user_choice = get_user_choice()
    computer_choice = get_computer_choice()
    winner = determine_winner(user_choice, computer_choice)
    display_results(user_choice, computer_choice, winner)