# -*- coding: utf-8 -*-
"""CodeSoft_Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p2m9rvbX1NcZe8rofg4daaOeYcG8uR76

Task:- 3  PASSWORD GENERATOR
"""

import random
import string

def generate_password(length):
    # Define character sets for different complexities
    lower_case = string.ascii_lowercase
    upper_case = string.ascii_uppercase
    digits = string.digits
    special_chars = string.punctuation

    # Combine character sets based on complexity
    all_chars = lower_case + upper_case + digits + special_chars

    # Ensure length is at least 8 characters
    length = max(length, 8)

    # Generate password
    password = ''.join(random.choice(all_chars) for _ in range(length))
    return password

def main():
    # Get user input for password length
    try:
        length = int(input("Enter the desired length of the password: "))
    except ValueError:
        print("Invalid input. Please enter a valid integer.")
        return

    # Generate and display the password
    password = generate_password(length)
    print("Generated Password:", password)

if __name__ == "__main__":
    main()

